src/OnlineShop.Web/Controllers/DynamicPermissionsTestController.cs
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Services.Admin;
using OnlineShop.ViewModels.Admin;
using OnlineShop.Web.Areas.Admin.Controllers;
using System.ComponentModel;

namespace OnlineShop.Web.Controllers
{
    /// <summary>
    /// More info: http://www.dotnettips.info/post/2581
    /// </summary>
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("کنترلر آزمایشی با سطح دسترسی پویا")]
    // [NoBrowserCache]
    public class DynamicPermissionsTestController : Controller
    {
        [DisplayName("ایندکس")]
        [BreadCrumb(Order = 1)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost] // More info: http://www.dotnettips.info/post/2468/ and http://www.dotnettips.info/post/2470/
        public IActionResult Index([FromBody]RoleViewModel model)
        {
            return Json(model);
        }

        [DisplayName("گزارش از لیست محصولات")]
        [BreadCrumb(Order = 1)]
        public IActionResult Products()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست سفارشات")]
        [BreadCrumb(Order = 1)]
        public IActionResult Orders()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست فروش")]
        [BreadCrumb(Order = 1)]
        public IActionResult Sells()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست خریداران")]
        [BreadCrumb(Order = 1)]
        public IActionResult Customers()
        {
            return View(viewName: "Index");
        }
    }
}

src/OnlineShop.Web/Views/DynamicPermissionsTest/Index.cshtml
@{
    ViewData["Title"] = "مثالی از یک صفحه‌ی با سطح دسترسی پویا";
}

<div class="alert alert-info mt-5">
    <a href="#" class="close" data-dismiss="alert">×</a>
    @ViewData["Title"] : @ViewContext.ActionDescriptor.DisplayName
</div>

<button type="submit" onclick="postData()" class="btn btn-info">
    ارسال جهت مشاهده request.DeserializeJsonBodyAsAsync
</button>

@section Scripts
{
    <script type="text/javascript">
        function postData() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Index","DynamicPermissionsTest")',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify({
                    Id: 1,
                    Name: 'Name1'
                }),
                success: function (result) {
                    console.log('Data received: ');
                    console.log(result);
                }
            });
        }
    </script>
}